# site settings
title: DLUB
subtitle: Portfolio
email: lubrano93@gmail.com
description: A showcase for practical applications of deep learning, artificial intelligence and computer vision.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: (

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# contact form settings
form_url: https://formspree.io/youremailaddress@gmail.com # endpoint URL to receive contact form submissions
form_email_name: _replyto # value of the "name" attribute in the "email" field

# social settings
500px_url:
facebook_url:
github_url: https://github.com/odiurd
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
